### ISSUE TITLE
question

### ISSUE THREAD

**Issue by yxt-DRL** [henbudidiao/UAV-path-planning#3]
博主您好，我运行main_SAC.py会出现下面问题，我在assignment文件下添加__init__.py文件也不行，请问这个问题改怎么解决呀

Traceback (most recent call last):
  File "D:\Pycharm\111\path planning\main_SAC.py", line 7, in <module>
    from rl_env.path_env import RlGame
  File "D:\Pycharm\111\path planning\rl_env\path_env.py", line 7, in <module>
    from assignment import constants as C
ImportError: cannot import name 'constants' from 'assignment' (D:\Pycharm\111\path planning\assignment\__init__.py)

**Comment by henbudidiao** [comment]
OK，知道了。我知道你很急，但是！！！你先别急。我到时候会出个视频教学的。

**Comment by yxt-DRL** [comment]
好滴，谢谢博主！

**Comment by xiaohaiRen** [comment]
up您好，请问是否会推出三维版本？
